
// ============ COMPLETE STYLES ============
const styles = StyleSheet.create({
  // Landing
  landingContainer: { flex: 1 },
  gradient: { flex: 1, paddingHorizontal: 24 },
  landingHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 16 },
  logoRow: { flexDirection: 'row', alignItems: 'center' },
  logoIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#25D366', justifyContent: 'center', alignItems: 'center' },
  logoText: { fontSize: 24, fontWeight: '700', color: '#1c1917', marginLeft: 12 },
  signInBtn: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, backgroundColor: 'rgba(37,211,102,0.1)' },
  signInText: { fontSize: 16, fontWeight: '600', color: '#25D366' },
  heroSection: { paddingTop: 40 },
  tagline: { fontSize: 36, fontWeight: '700', color: '#1c1917', lineHeight: 44 },
  taglineAccent: { fontSize: 36, fontWeight: '700', color: '#25D366', lineHeight: 44, marginBottom: 16 },
  heroDesc: { fontSize: 18, color: '#57534e', lineHeight: 28, marginBottom: 32 },
  ctaButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#25D366', paddingVertical: 16, paddingHorizontal: 32, borderRadius: 16, alignSelf: 'flex-start' },
  ctaText: { fontSize: 18, fontWeight: '600', color: '#ffffff', marginRight: 8 },
  featuresRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 40 },
  featureCard: { flex: 1, backgroundColor: '#ffffff', borderRadius: 16, padding: 16, marginHorizontal: 4, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  featureIcon: { width: 48, height: 48, borderRadius: 12, backgroundColor: 'rgba(37,211,102,0.1)', justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  featureTitle: { fontSize: 13, fontWeight: '600', color: '#1c1917', textAlign: 'center' },
  featureDesc: { fontSize: 11, color: '#78716c', textAlign: 'center', marginTop: 2 },
  trustBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 'auto', marginBottom: 24, paddingVertical: 12 },
  trustText: { fontSize: 14, fontWeight: '600', color: '#57534e', marginLeft: 8, letterSpacing: 0.5 },

  // Role Selection
  roleContainer: { flex: 1, backgroundColor: '#ffffff', paddingHorizontal: 24 },
  backBtn: { width: 44, height: 44, borderRadius: 12, backgroundColor: '#f5f5f4', justifyContent: 'center', alignItems: 'center', marginTop: 16 },
  roleTitle: { fontSize: 32, fontWeight: '700', color: '#1c1917', marginTop: 32 },
  roleSubtitle: { fontSize: 18, color: '#78716c', marginTop: 8, marginBottom: 32 },
  rolesContainer: { gap: 16 },
  roleCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 20, padding: 20, borderWidth: 1, borderColor: '#e7e5e4', marginBottom: 16 },
  roleIcon: { width: 64, height: 64, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
  roleTextContainer: { flex: 1, marginLeft: 16 },
  roleCardTitle: { fontSize: 20, fontWeight: '600', color: '#1c1917', marginBottom: 4 },
  roleCardDesc: { fontSize: 14, color: '#78716c', lineHeight: 20 },
  roleFooter: { marginTop: 'auto', marginBottom: 32, alignItems: 'center' },
  roleFooterText: { fontSize: 14, color: '#a8a29e' },

  // Auth
  authContainer: { flex: 1, backgroundColor: '#ffffff', paddingHorizontal: 24 },
  roleTag: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, marginTop: 24, marginBottom: 16 },
  roleTagText: { fontSize: 14, fontWeight: '600' },
  authTitle: { fontSize: 32, fontWeight: '700', color: '#1c1917' },
  authSubtitle: { fontSize: 16, color: '#78716c', marginTop: 8, marginBottom: 32 },
  socialBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e7e5e4', borderRadius: 12, paddingVertical: 14, marginBottom: 12 },
  socialText: { fontSize: 16, fontWeight: '500', color: '#1c1917', marginLeft: 12 },
  divider: { flexDirection: 'row', alignItems: 'center', marginVertical: 24 },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#e7e5e4' },
  dividerText: { marginHorizontal: 16, fontSize: 14, color: '#a8a29e' },
  inputLabel: { fontSize: 14, fontWeight: '500', color: '#57534e', marginBottom: 8 },
  input: { backgroundColor: '#f5f5f4', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, marginBottom: 16 },
  loginBtn: { borderRadius: 12, paddingVertical: 16, alignItems: 'center', marginTop: 8 },
  loginBtnText: { fontSize: 16, fontWeight: '600', color: '#ffffff' },
  toggleAuth: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 24, gap: 4 },
  toggleAuthText: { fontSize: 14, color: '#78716c' },
  toggleAuthLink: { fontSize: 14, fontWeight: '600' },

  // Home Container
  homeContainer: { flex: 1 },
  
  // Offline State
  offlineContainer: { flex: 1, padding: 24 },
  offlineHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 32 },
  caregiverPhoto: { width: 56, height: 56, borderRadius: 16, marginRight: 16 },
  greeting: { fontSize: 14, marginBottom: 2 },
  caregiverName: { fontSize: 24, fontWeight: '700' },
  patientCardOffline: { borderRadius: 24, padding: 20, borderWidth: 1, marginBottom: 40 },
  patientCardLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 16 },
  patientCardRow: { flexDirection: 'row', alignItems: 'center' },
  patientPhotoLarge: { width: 64, height: 64, borderRadius: 18 },
  patientCardInfo: { flex: 1, marginLeft: 16 },
  patientName: { fontSize: 20, fontWeight: '700', marginBottom: 4 },
  patientAge: { fontSize: 14 },
  startShiftSection: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  offlineText: { fontSize: 14, marginBottom: 8 },
  startShiftTitle: { fontSize: 20, fontWeight: '600', marginBottom: 32 },
  goButton: { width: 160, height: 160, borderRadius: 80, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  goButtonPulse: { position: 'absolute', width: 180, height: 180, borderRadius: 90, backgroundColor: 'rgba(244,63,94,0.2)' },
  goButtonInner: { width: 140, height: 140, borderRadius: 70, justifyContent: 'center', alignItems: 'center' },
  tasksScheduled: { fontSize: 14 },

  // Patient Header (Online)
  patientHeaderContainer: { position: 'relative', height: 180 },
  patientHeaderPhoto: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover' },
  patientHeaderGradient: { position: 'absolute', width: '100%', height: '100%' },
  patientHeaderInfo: { position: 'absolute', bottom: 50, left: 20, right: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  patientHeaderName: { fontSize: 20, fontWeight: '700', color: '#ffffff' },
  patientHeaderAge: { fontSize: 14, color: 'rgba(255,255,255,0.9)' },

  // Vitals
  vitalsContainer: { paddingHorizontal: 20, marginTop: -24, zIndex: 10 },
  vitalsGrid: { flexDirection: 'row', gap: 8 },
  vitalCard: { flex: 1, padding: 12, borderRadius: 16, borderWidth: 1, alignItems: 'center' },
  vitalIcon: { width: 36, height: 36, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  vitalValue: { fontSize: 16, fontWeight: '700' },
  vitalLabel: { fontSize: 10, marginTop: 2 },

  // Progress
  progressSection: { paddingHorizontal: 20, paddingVertical: 20 },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  progressLabel: { fontSize: 14, fontWeight: '500' },
  progressCount: { fontSize: 14, fontWeight: '700' },
  progressBarBg: { height: 8, borderRadius: 4, overflow: 'hidden' },
  progressBarFill: { height: '100%', backgroundColor: '#25D366', borderRadius: 4 },

  // Task Tabs
  taskTabs: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, marginBottom: 16, gap: 16 },
  tabText: { fontSize: 14, fontWeight: '600' },
  tabBadge: { position: 'absolute', top: -8, right: -12, width: 16, height: 16, borderRadius: 8, backgroundColor: '#f43f5e', justifyContent: 'center', alignItems: 'center' },
  tabBadgeText: { fontSize: 10, fontWeight: '700', color: '#ffffff' },
  tabDivider: { flex: 1, height: 1 },

  // Task List
  taskList: { paddingHorizontal: 20, paddingBottom: 100 },
  
  // Task Card
  taskCard: { borderRadius: 16, overflow: 'hidden', marginBottom: 12, borderWidth: 1 },
  taskStripe: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 4 },
  taskContent: { flexDirection: 'row', paddingLeft: 16, paddingRight: 16, paddingVertical: 16 },
  taskMain: { flex: 1 },
  taskHeader: { marginBottom: 6 },
  taskTitle: { fontSize: 16, fontWeight: '600' },
  taskTitleCompleted: { textDecorationLine: 'line-through', opacity: 0.6 },
  taskMeta: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  taskTimeRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  taskTime: { fontSize: 13 },
  photoBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, gap: 4 },
  photoBadgeText: { fontSize: 11, fontWeight: '500' },
  taskNote: { fontSize: 13, fontStyle: 'italic', marginTop: 8 },
  taskRight: { flexDirection: 'row', alignItems: 'center', gap: 10, marginLeft: 10 },
  taskPhoto: { width: 48, height: 48, borderRadius: 12 },
  taskExpandIcon: { width: 32, height: 32, borderRadius: 16, borderWidth: 2, justifyContent: 'center', alignItems: 'center' },
  taskExpanded: { paddingHorizontal: 16, paddingBottom: 16, paddingTop: 16, borderTopWidth: 1 },
  taskExpandedSection: { marginBottom: 16 },
  taskExpandedLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 },
  taskExpandedText: { fontSize: 14, lineHeight: 22 },
  startTaskBtn: { backgroundColor: '#25D366', paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  startTaskBtnText: { fontSize: 15, fontWeight: '600', color: '#ffffff' },

  // Request Card
  requestCard: { borderRadius: 16, overflow: 'hidden', marginBottom: 12, borderWidth: 1 },
  requestStripe: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 4 },
  requestContent: { paddingLeft: 16, paddingRight: 16, paddingVertical: 16 },
  requestHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  requestBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  requestBadgeText: { fontSize: 10, fontWeight: '700', letterSpacing: 0.5 },
  requestTime: { fontSize: 13 },
  requestTitle: { fontSize: 16, fontWeight: '600', marginBottom: 6 },
  requestDesc: { fontSize: 14, lineHeight: 20, marginBottom: 6 },
  requestBy: { fontSize: 12, fontStyle: 'italic', marginBottom: 16 },
  requestActions: { flexDirection: 'row', gap: 12 },
  requestDeclineBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, borderWidth: 1, alignItems: 'center' },
  requestDeclineText: { fontSize: 14, fontWeight: '600' },
  requestAcceptBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, backgroundColor: '#25D366', alignItems: 'center' },
  requestAcceptText: { fontSize: 14, fontWeight: '600', color: '#ffffff' },

  // Empty State
  emptyState: { padding: 40, borderRadius: 24, alignItems: 'center', borderWidth: 1 },
  emptyStateText: { fontSize: 14, marginTop: 12 },

  // FAB
  fab: { position: 'absolute', right: 20, bottom: 100, width: 60, height: 60, borderRadius: 30, backgroundColor: '#25D366', justifyContent: 'center', alignItems: 'center', shadowColor: '#25D366', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 8 },

  // Modal
  modalContainer: { flex: 1 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1 },
  modalTitle: { fontSize: 18, fontWeight: '600' },
  modalContent: { flex: 1, padding: 20 },

  // Task Completion Modal
  taskSummary: { padding: 16, borderRadius: 16, marginBottom: 20, borderWidth: 1 },
  taskSummaryTitle: { fontSize: 18, fontWeight: '600', marginBottom: 6 },
  taskSummaryDesc: { fontSize: 14, lineHeight: 20 },
  photoSection: { marginBottom: 20 },
  photoLabel: { fontSize: 16, fontWeight: '600', marginBottom: 12 },
  photoCapture: { height: 160, borderRadius: 16, borderWidth: 2, borderStyle: 'dashed', justifyContent: 'center', alignItems: 'center', gap: 12 },
  photoCaptureText: { fontSize: 16, fontWeight: '500' },
  noteSection: { marginBottom: 20 },
  noteLabel: { fontSize: 16, fontWeight: '600', marginBottom: 12 },
  noteInput: { height: 120, borderRadius: 16, padding: 16, fontSize: 15, borderWidth: 1 },
  completeBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#25D366', paddingVertical: 16, borderRadius: 16, gap: 10 },
  completeBtnText: { fontSize: 17, fontWeight: '600', color: '#ffffff' },

  // Profile Modal
  profileCard: { alignItems: 'center', padding: 24, borderRadius: 20, marginBottom: 20 },
  profilePhoto: { width: 100, height: 100, borderRadius: 28, marginBottom: 16 },
  profileName: { fontSize: 24, fontWeight: '700', marginBottom: 4 },
  profileAge: { fontSize: 16 },
  profileSection: { marginBottom: 20 },
  profileSectionTitle: { fontSize: 16, fontWeight: '600', marginBottom: 12 },
  profileSectionCard: { borderRadius: 16, overflow: 'hidden' },
  profileItem: { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 12 },
  profileItemColumn: { flexDirection: 'column', alignItems: 'flex-start' },
  profileItemHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  profileItemText: { fontSize: 15, flex: 1 },
  profileItemSub: { fontSize: 13, marginTop: 4, marginLeft: 30 },
  emergencyCard: { borderRadius: 16, padding: 16 },
  emergencyHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 4 },
  emergencyName: { fontSize: 17, fontWeight: '600' },
  emergencyRelation: { fontSize: 14, marginLeft: 30, marginBottom: 14 },
  callButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: 12, gap: 10 },
  callButtonText: { fontSize: 16, fontWeight: '600', color: '#ffffff' },

  // Vitals Modal
  vitalTabs: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, gap: 8 },
  vitalTab: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, gap: 8 },
  vitalTabText: { fontSize: 14, fontWeight: '600' },
  vitalCurrentCard: { alignItems: 'center', padding: 24, borderRadius: 20, marginBottom: 24 },
  vitalCurrentLabel: { fontSize: 14, marginBottom: 8 },
  vitalCurrentValue: { fontSize: 48, fontWeight: '700' },
  vitalCurrentUnit: { fontSize: 20, fontWeight: '400' },
  vitalCurrentTime: { fontSize: 14, marginTop: 8 },
  vitalHistoryTitle: { fontSize: 18, fontWeight: '600', marginBottom: 14 },
  vitalHistoryCard: { borderRadius: 16, overflow: 'hidden' },
  vitalHistoryItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16 },
  vitalHistoryDate: { fontSize: 14, width: 50 },
  vitalHistoryValue: { fontSize: 16, fontWeight: '600', flex: 1, textAlign: 'center' },
  vitalHistoryTime: { fontSize: 13, width: 80, textAlign: 'right' },
  recordVitalBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#25D366', paddingVertical: 16, borderRadius: 16, marginTop: 24, gap: 8 },
  recordVitalBtnText: { fontSize: 16, fontWeight: '600', color: '#ffffff' },

  // Incident Screen
  incidentScroll: { paddingHorizontal: 20, paddingBottom: 100 },
  screenTitle: { fontSize: 28, fontWeight: '700', marginTop: 16 },
  screenSubtitle: { fontSize: 15, marginTop: 4, marginBottom: 20 },
  newIncidentBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f43f5e', padding: 20, borderRadius: 20, marginBottom: 20 },
  newIncidentContent: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  newIncidentIcon: { width: 50, height: 50, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  newIncidentTitle: { fontSize: 18, fontWeight: '600', color: '#ffffff' },
  newIncidentSubtitle: { fontSize: 14, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  summaryRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  summaryCard: { flex: 1, padding: 16, borderRadius: 16, alignItems: 'center' },
  summaryNum: { fontSize: 28, fontWeight: '700' },
  summaryLabel: { fontSize: 13, marginTop: 4 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { fontSize: 18, fontWeight: '600' },
  countBadge: { marginLeft: 8, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, backgroundColor: '#f43f5e' },
  countBadgeText: { fontSize: 12, fontWeight: '700', color: '#ffffff' },
  incidentCard: { borderRadius: 16, padding: 16, marginBottom: 12, borderWidth: 1 },
  incidentCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  incidentCardLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  incidentTypeIcon: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  statusBadgeText: { fontSize: 10, fontWeight: '700', color: '#ffffff', letterSpacing: 0.5 },
  incidentDate: { fontSize: 13 },
  incidentCardTitle: { fontSize: 17, fontWeight: '600', marginBottom: 6 },
  incidentCardDesc: { fontSize: 14, lineHeight: 20, marginBottom: 8 },
  incidentCardBy: { fontSize: 12, fontStyle: 'italic' },

  // Incident Form
  incidentFormHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1 },
  incidentFormHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  incidentFormIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: 'rgba(244,63,94,0.2)', justifyContent: 'center', alignItems: 'center' },
  incidentFormTitle: { fontSize: 18, fontWeight: '600' },
  incidentFormStep: { fontSize: 12 },
  cancelBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 10 },
  cancelBtnText: { fontSize: 14, fontWeight: '500' },
  stepProgress: { flexDirection: 'row', paddingHorizontal: 20, paddingVertical: 16, gap: 6 },
  stepDot: { flex: 1, height: 4, borderRadius: 2 },
  incidentFormContent: { flex: 1, padding: 20 },
  stepTitle: { fontSize: 22, fontWeight: '600', marginBottom: 20 },
  typeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  typeCard: { width: '47%', padding: 20, borderRadius: 16, alignItems: 'center', borderWidth: 1 },
  typeIconContainer: { width: 56, height: 56, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  typeLabel: { fontSize: 15, fontWeight: '500' },
  severityList: { gap: 12 },
  severityCard: { flexDirection: 'row', alignItems: 'center', padding: 20, borderRadius: 16, borderWidth: 1, gap: 14 },
  severityDot: { width: 12, height: 12, borderRadius: 6 },
  severityLabel: { fontSize: 16, fontWeight: '500' },
  stepNav: { flexDirection: 'row', gap: 12, marginTop: 24 },
  backStepBtn: { flex: 1, paddingVertical: 16, borderRadius: 16, borderWidth: 1, alignItems: 'center' },
  backStepBtnText: { fontSize: 16, fontWeight: '600' },
  nextBtn: { flex: 1, paddingVertical: 16, borderRadius: 16, backgroundColor: '#f43f5e', alignItems: 'center' },
  nextBtnText: { fontSize: 16, fontWeight: '600', color: '#ffffff' },
  textArea: { height: 120, borderRadius: 16, padding: 16, fontSize: 15, borderWidth: 1, marginBottom: 20 },
  reviewCard: { borderRadius: 16, padding: 16, marginBottom: 20 },
  reviewRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  reviewRowFull: { marginBottom: 16 },
  reviewLabel: { fontSize: 14 },
  reviewValue: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  reviewValueText: { fontSize: 15, fontWeight: '500' },
  reviewDesc: { fontSize: 15, lineHeight: 22, marginTop: 6 },
  severityBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  severityBadgeText: { fontSize: 13, fontWeight: '600' },
  toggleCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderRadius: 16, marginBottom: 20 },
  toggleContent: { flexDirection: 'row', alignItems: 'center', gap: 14, flex: 1 },
  toggleText: { flex: 1 },
  toggleTitle: { fontSize: 16, fontWeight: '500' },
  toggleDesc: { fontSize: 13, marginTop: 2 },
  submitBtn: { flex: 2, paddingVertical: 16, borderRadius: 16, backgroundColor: '#f43f5e', alignItems: 'center' },
  submitBtnText: { fontSize: 16, fontWeight: '600', color: '#ffffff' },
  successContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  successCard: { width: '100%', maxWidth: 320, padding: 32, borderRadius: 24, alignItems: 'center' },
  successIcon: { width: 80, height: 80, borderRadius: 40, backgroundColor: 'rgba(37,211,102,0.2)', justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
  successTitle: { fontSize: 24, fontWeight: '700', marginBottom: 12 },
  successDesc: { fontSize: 15, textAlign: 'center', lineHeight: 22, marginBottom: 24 },
  successBtn: { width: '100%', paddingVertical: 16, borderRadius: 16, backgroundColor: '#25D366', alignItems: 'center' },
  successBtnText: { fontSize: 16, fontWeight: '600', color: '#ffffff' },

  // Messages
  messageHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 16, paddingBottom: 16 },
  newMessageBtn: { width: 44, height: 44, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  patientContext: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 20, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, gap: 8, marginBottom: 16 },
  patientContextText: { fontSize: 13 },
  messageList: { paddingHorizontal: 20, paddingBottom: 100 },
  conversationCard: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 16, marginBottom: 12 },
  avatar: { width: 50, height: 50, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  avatarText: { fontSize: 16, fontWeight: '600', color: '#ffffff' },
  conversationInfo: { flex: 1, marginLeft: 14 },
  conversationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  conversationName: { fontSize: 16, fontWeight: '600' },
  conversationTime: { fontSize: 12 },
  conversationRole: { fontSize: 11, marginTop: 2 },
  conversationMessage: { fontSize: 14, marginTop: 6 },
  unreadBadge: { width: 24, height: 24, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginLeft: 10 },
  unreadText: { fontSize: 12, fontWeight: '700', color: '#ffffff' },

  // Shifts
  shiftScroll: { paddingHorizontal: 20, paddingBottom: 100 },
  shiftCard: { borderRadius: 24, padding: 20, marginTop: 20, borderWidth: 1 },
  shiftCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  shiftStatus: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  shiftStatusText: { fontSize: 17, fontWeight: '600' },
  liveBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, gap: 6 },
  liveIndicator: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#ffffff' },
  liveText: { fontSize: 11, fontWeight: '700', color: '#ffffff', letterSpacing: 0.5 },
  shiftDetails: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 20 },
  shiftDetailRow: { width: '50%', flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
  shiftDetailText: {},
  shiftDetailLabel: { fontSize: 11, color: 'rgba(255,255,255,0.7)' },
  shiftDetailValue: { fontSize: 15, fontWeight: '600', color: '#ffffff' },
  shiftToggleBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, borderRadius: 14, gap: 10 },
  shiftToggleBtnText: { fontSize: 17, fontWeight: '600', color: '#ffffff' },
  quickActionsGrid: { flexDirection: 'row', gap: 12, marginTop: 12 },
  quickActionCard: { flex: 1, padding: 16, borderRadius: 16, alignItems: 'center' },
  quickActionIcon: { width: 48, height: 48, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  quickActionLabel: { fontSize: 13, fontWeight: '500', textAlign: 'center' },
  recentShiftsCard: { borderRadius: 16, overflow: 'hidden', marginTop: 12 },
  shiftRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16 },
  shiftDate: { fontSize: 15, fontWeight: '600', marginBottom: 4 },
  shiftHours: { fontSize: 13 },
  shiftEarnings: { fontSize: 16, fontWeight: '600' },
  earningsCard: { borderRadius: 16, padding: 20, alignItems: 'center', marginTop: 24 },
  earningsHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  earningsTitle: { fontSize: 16, fontWeight: '600' },
  earningsAmount: { fontSize: 36, fontWeight: '700' },
  earningsSubtext: { fontSize: 14, marginTop: 4 },

  // Menu
  menuScroll: { paddingHorizontal: 20, paddingBottom: 40 },
  profileCardMenu: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 20, marginTop: 20, marginBottom: 16 },
  profilePhotoMenu: { width: 60, height: 60, borderRadius: 16 },
  profileInfoMenu: { flex: 1, marginLeft: 16 },
  profileNameMenu: { fontSize: 18, fontWeight: '600', marginBottom: 4 },
  profileRoleMenu: { fontSize: 14 },
  themeToggle: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderRadius: 16, marginBottom: 16 },
  themeToggleLeft: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  themeIcon: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  themeLabel: { fontSize: 16, fontWeight: '500' },
  themeValue: { fontSize: 13, marginTop: 2 },
  menuContainer: { borderRadius: 16, overflow: 'hidden', marginBottom: 24 },
  menuItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16 },
  menuItemLeft: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  menuIcon: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  menuLabel: { fontSize: 16, fontWeight: '500' },
  signOutBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 16, borderRadius: 16, gap: 10 },
  signOutText: { fontSize: 16, fontWeight: '600' },
  appVersion: { textAlign: 'center', fontSize: 13, marginTop: 24 },

  // AI Copilot
  copilotContainer: { flex: 1 },
  copilotHeader: { flexDirection: 'row', alignItems: 'center', padding: 16, borderBottomWidth: 1 },
  copilotBackBtn: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  copilotHeaderTitle: { flex: 1, flexDirection: 'row', alignItems: 'center', marginLeft: 8, gap: 12 },
  copilotIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#25D366', justifyContent: 'center', alignItems: 'center' },
  copilotTitle: { fontSize: 17, fontWeight: '600' },
  copilotSubtitle: { fontSize: 13 },
  messagesList: { padding: 16, paddingBottom: 8 },
  messageBubble: { maxWidth: '85%', padding: 14, borderRadius: 18, marginBottom: 12 },
  userBubble: { alignSelf: 'flex-end', borderBottomRightRadius: 4 },
  aiBubble: { alignSelf: 'flex-start', borderBottomLeftRadius: 4, flexDirection: 'row', alignItems: 'flex-start' },
  aiAvatarSmall: { width: 24, height: 24, borderRadius: 8, backgroundColor: '#25D366', justifyContent: 'center', alignItems: 'center', marginRight: 10, marginTop: 2 },
  messageText: { fontSize: 15, lineHeight: 22, flex: 1 },
  loadingBubble: { alignSelf: 'flex-start', marginLeft: 16, marginBottom: 12, padding: 14, borderRadius: 18 },
  loadingDots: { flexDirection: 'row', gap: 6 },
  loadingDot: { width: 8, height: 8, borderRadius: 4 },
  suggestionsContainer: { paddingVertical: 8 },
  suggestionsList: { paddingHorizontal: 16, gap: 8 },
  suggestionChip: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, borderWidth: 1, marginRight: 8 },
  suggestionText: { fontSize: 14, fontWeight: '500' },
  inputBar: { flexDirection: 'row', alignItems: 'flex-end', padding: 12, borderTopWidth: 1, gap: 10 },
  chatInput: { flex: 1, minHeight: 44, maxHeight: 100, borderRadius: 22, paddingHorizontal: 18, paddingVertical: 12, fontSize: 16 },
  sendBtn: { width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
});

// ============ APP ENTRY ============
export default function App() {
  return (
    <ThemeProvider>
      <AuthProvider>
        <AppNavigator />
      </AuthProvider>
    </ThemeProvider>
  );
}
